name: Dockerize Application

on:
  push:
    branches:
      - main

jobs:
  dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build and Dockerize
        run: |
          ./gradlew dockerize

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t your-dockerhub-username/your-repo-name:latest .
          docker push your-dockerhub-username/your-repo-name:latest